### ISSUE TITLE
Hosting the addoon outside Curse

### ISSUE THREAD

**Issue by Floppy012** [Trufi/TrufiGCD#17]
Overwolf is introducing the Curse V2 API. It will not support third party addons such as WoWUp (because WoWUp is partnered with Wago and therefore Curse decided to deny the API Key application because of competition)

https://www.wowhead.com/news/ads-revenue-and-api-wowup-and-overwolf-split-over-addon-development-325912

I am playing WoW on Linux and Curse does not have a version of their launcher for Linux (although an alpha of something is scheduled for the future, the way Overwolf is approaching the whole API change isn't very community friendly which makes me most likely not use any of their products in the near future)

WoWUp is one of the more common updaters used. WoWUp supports multiple Addon sources such as:

- TukUI
- WowInterface
- wago.io

They also support pulling the addon directly from GitHub/GitLab Releases (https://wowup.io/guide/wowup/hub). If you are interested in monetization, then I suggest you to use wago.io. They provide monetization features.

It would be really cool to have the Addon available outside Curse <3

**Comment by Trufi** [comment]
Hey, a little too late but I updated the addon on the wowinterface site
