### ISSUE TITLE
Non-GCD spells not captured (Mage - Fire Blast cast during Fireball cast)

### ISSUE THREAD

**Issue by Dayzin** [Trufi/TrufiGCD#6]
Spells that can be cast while casting other spells are not being tracked.

An example of this is a Mage casting Fire Blast or Combustion during a Fireball cast.

**Comment by Trufi** [comment]
This should be fixed in https://github.com/Trufi/TrufiGCD/commit/546eb9a7d34c60fbeb1c63efff659a7afac56142
